FROM node:24.13.0-alpine
WORKDIR /app

RUN corepack enable && corepack prepare pnpm@10.27.0 --activate

# Manifests do workspace para pnpm install reconhecer o monorepo
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./

COPY app-backend/package.json ./app-backend/
COPY app-web/package.json ./app-web/
COPY app-web/tsconfig.json app-web/next.config.ts ./app-web/

RUN pnpm install --frozen-lockfile

WORKDIR /app/app-web

CMD ["pnpm", "dev"]
