@baseUrl = http://localhost:3012/auth
@userId = 00000000-0000-4000-a000-000000000001

### Create a new user
POST {{baseUrl}}/callback
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe@example.com",
  "externalIntegrationUser": "johndoe_ext",
  "role": "APPROVER",
  "active": true,
  "approvalLimit": 5000,
  "companyIds": [],
  "substituteIds": []
}